import { getStateImage } from "@/components/state/stateImageMap";

export const DEFAULT_PACKAGE_IMAGE =
  "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=900&q=80";

/** Verified static images per package — avoids broken remote URLs. */
const PACKAGE_IMAGE_BY_ID = {
  "ladakh-escape": getStateImage("Ladakh"),
  "himachal-honeymoon": getStateImage("Himachal Pradesh"),
  "rajasthan-heritage": getStateImage("Rajasthan"),
  "kerala-backwaters": getStateImage("Kerala"),
  "kashmir-paradise": getStateImage("Jammu & Kashmir"),
  "goa-beach-retreat": getStateImage("Goa"),
  "spiti-adventure": "https://images.pexels.com/photos/32702512/pexels-photo-32702512.jpeg",
  "golden-triangle": "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=900&q=80",
  "uttarakhand-char-dham": getStateImage("Uttarakhand"),
  "north-east-explorer": getStateImage("Meghalaya"),
  "andaman-island": "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=900&q=80",
  "varanasi-spiritual": "https://images.unsplash.com/photo-1583397864745-f59ef28178cf?w=900&q=80",
  "gujarat-rann": getStateImage("Gujarat"),
  "ooty-nilgiris": getStateImage("Tamil Nadu"),
  "dubai-luxury": "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=900&q=80",
  "nepal-himalayan": "https://images.pexels.com/photos/417173/pexels-photo-417173.jpeg",
  "sikkim-darjeeling": getStateImage("Sikkim"),
  "thailand-tropical": getStateImage("Thailand"),
  "bhutan-serenity": "https://images.unsplash.com/photo-1589308078059-141d08954a05?w=900&q=80",
  "maldives-paradise": "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=900&q=80",
  "singapore-city": "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=900&q=80",
  "malaysia-twin": "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=900&q=80",
  "karnataka-heritage": getStateImage("Karnataka"),
  "punjab-golden": getStateImage("Punjab"),
  "assam-wildlife": getStateImage("Assam"),
  "corbett-wildlife": getStateImage("Uttarakhand"),
  "hyderabad-heritage": getStateImage("Telangana"),
  "bali-retreat": "https://images.pexels.com/photos/2387873/pexels-photo-2387873.jpeg",
  "sri-lanka-circle": getStateImage("Sri Lanka"),
  "vietnam-highlights": "https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=900&q=80",
  "mumbai-getaway": getStateImage("Maharashtra"),
  "coorg-nature": getStateImage("Karnataka"),
  "pondicherry-coastal": getStateImage("Pondicherry"),
};

export function getPackageImage(pkg) {
  if (!pkg) return DEFAULT_PACKAGE_IMAGE;
  return (
    PACKAGE_IMAGE_BY_ID[pkg.id] ||
    getStateImage(pkg.state) ||
    getStateImage(pkg.location) ||
    DEFAULT_PACKAGE_IMAGE
  );
}

export const TOUR_PACKAGES = [
  {
    id: "ladakh-escape",
    slug: "ladakh-escape-7n",
    title: "Ladakh Escape",
    subtitle: "Leh · Nubra · Pangong Lake",
    location: "Ladakh",
    state: "Ladakh",
    duration: "6N / 7D",
    price: 28999,
    originalPrice: 34999,
    rating: 4.9,
    reviews: 186,
    badge: "Best Seller",
    famous: true,
    country: "India",
    image:
      "https://images.unsplash.com/photo-1589308078059-141d08954a05?w=900&q=80",
    highlights: ["Pangong Lake", "Nubra Valley", "Khardung La"],
    inclusions: ["Hotels", "Breakfast", "Transfers", "Permits"],
    groupSize: "2–12 travellers",
    description:
      "High-altitude adventure through monasteries, sand dunes, and the iconic blue waters of Pangong.",
  },
  {
    id: "himachal-honeymoon",
    slug: "himachal-honeymoon-5n",
    title: "Himachal Honeymoon",
    subtitle: "Shimla · Manali · Kullu",
    location: "Himachal Pradesh",
    state: "Himachal Pradesh",
    duration: "4N / 5D",
    price: 22499,
    originalPrice: 26999,
    rating: 4.8,
    reviews: 142,
    badge: "Couples Favourite",
    famous: true,
    country: "India",
    image:
      "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=900&q=80",
    highlights: ["Romantic stays", "Solang Valley", "River-side dinners"],
    inclusions: ["4★ Hotels", "Breakfast & dinner", "Private cab"],
    groupSize: "2 travellers",
    description:
      "Snow-capped peaks, cosy retreats, and candlelit evenings crafted for couples.",
  },
  {
    id: "rajasthan-heritage",
    slug: "rajasthan-heritage-6n",
    title: "Rajasthan Heritage",
    subtitle: "Jaipur · Jodhpur · Udaipur",
    location: "Rajasthan",
    state: "Rajasthan",
    duration: "5N / 6D",
    price: 25999,
    originalPrice: 30999,
    rating: 4.9,
    reviews: 203,
    badge: "Heritage Pick",
    famous: true,
    country: "India",
    image:
      "https://images.unsplash.com/photo-1477587450883-47145ad9425d?w=900&q=80",
    highlights: ["Palace stays", "Desert safari", "City palace tours"],
    inclusions: ["Heritage hotels", "Breakfast", "Guided tours"],
    groupSize: "2–15 travellers",
    description:
      "Royal forts, vibrant bazaars, and sunset views across the Land of Kings.",
  },
  {
    id: "kerala-backwaters",
    slug: "kerala-backwaters-5n",
    title: "Kerala Backwaters",
    subtitle: "Munnar · Alleppey · Kochi",
    location: "Kerala",
    state: "Kerala",
    duration: "4N / 5D",
    price: 23999,
    originalPrice: 28499,
    rating: 4.8,
    reviews: 167,
    badge: "Serene Escape",
    country: "India",
    image:
      "https://images.unsplash.com/photo-1602216052126-53eaaec9faea?w=900&q=80",
    highlights: ["Houseboat cruise", "Tea gardens", "Ayurveda spa"],
    inclusions: ["Resort & houseboat", "All meals", "Transfers"],
    groupSize: "2–10 travellers",
    description:
      "Lush hills, tranquil backwaters, and rejuvenating wellness experiences.",
  },
  {
    id: "kashmir-paradise",
    slug: "kashmir-paradise-6n",
    title: "Kashmir Paradise",
    subtitle: "Srinagar · Gulmarg · Pahalgam",
    location: "Kashmir",
    state: "Jammu & Kashmir",
    duration: "5N / 6D",
    price: 27499,
    originalPrice: 32999,
    rating: 4.9,
    reviews: 198,
    badge: "Top Rated",
    famous: true,
    country: "India",
    image:
      "https://images.unsplash.com/photo-1568667256542-548cfa66a59f?w=900&q=80",
    highlights: ["Shikara ride", "Gondola ride", "Mughal gardens"],
    inclusions: ["Houseboat & hotel", "Breakfast", "Sightseeing"],
    groupSize: "2–12 travellers",
    description:
      "Dal Lake mornings, alpine meadows, and the timeless charm of the valley.",
  },
  {
    id: "goa-beach-retreat",
    slug: "goa-beach-retreat-4n",
    title: "Goa Beach Retreat",
    subtitle: "North Goa · South Goa",
    location: "Goa",
    state: "Goa",
    duration: "3N / 4D",
    price: 16999,
    originalPrice: 20999,
    rating: 4.7,
    reviews: 124,
    badge: "Weekend Special",
    country: "India",
    image:
      "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=900&q=80",
    highlights: ["Beach resorts", "Water sports", "Sunset cruise"],
    inclusions: ["Beach resort", "Breakfast", "Airport transfers"],
    groupSize: "2–8 travellers",
    description:
      "Golden sands, coastal cuisine, and laid-back luxury by the Arabian Sea.",
  },
  {
    id: "spiti-adventure",
    slug: "spiti-valley-8n",
    title: "Spiti Valley Adventure",
    subtitle: "Manali · Kaza · Key Monastery",
    location: "Spiti Valley",
    state: "Himachal Pradesh",
    duration: "7N / 8D",
    price: 31999,
    originalPrice: 37999,
    rating: 4.9,
    reviews: 89,
    badge: "Adventure",
    famous: true,
    country: "India",
    image:
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=900&q=80",
    highlights: ["Key Monastery", "Chandratal Lake", "High passes"],
    inclusions: ["Homestays & camps", "All meals", "4×4 vehicle"],
    groupSize: "4–10 travellers",
    description:
      "Raw Himalayan landscapes, ancient monasteries, and offbeat trails for explorers.",
  },
  {
    id: "golden-triangle",
    slug: "golden-triangle-5n",
    title: "Golden Triangle",
    subtitle: "Delhi · Agra · Jaipur",
    location: "North India",
    state: "Delhi",
    duration: "4N / 5D",
    price: 19999,
    originalPrice: 24499,
    rating: 4.8,
    reviews: 256,
    badge: "Classic Route",
    famous: true,
    country: "India",
    image:
      "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=900&q=80",
    highlights: ["Taj Mahal", "Amber Fort", "Old Delhi walk"],
    inclusions: ["3★ Hotels", "Breakfast", "AC transport"],
    groupSize: "2–20 travellers",
    description:
      "India's most iconic circuit — monuments, culture, and cuisine in one journey.",
  },
  {
    id: "uttarakhand-char-dham",
    slug: "uttarakhand-char-dham-9n",
    title: "Uttarakhand Char Dham",
    subtitle: "Yamunotri · Gangotri · Kedarnath · Badrinath",
    location: "Uttarakhand",
    state: "Uttarakhand",
    duration: "8N / 9D",
    price: 34999,
    originalPrice: 41999,
    rating: 4.9,
    reviews: 112,
    badge: "Spiritual",
    famous: true,
    country: "India",
    image:
      "https://images.pexels.com/photos/14149541/pexels-photo-14149541.jpeg",
    highlights: ["Char Dham yatra", "Himalayan drives", "Temple darshan"],
    inclusions: ["Hotels", "Meals", "Heli options", "Transfers"],
    groupSize: "4–20 travellers",
    description:
      "A sacred Himalayan pilgrimage covering all four dhams with comfortable stays and guided support.",
  },
  {
    id: "north-east-explorer",
    slug: "north-east-explorer-7n",
    title: "North East Explorer",
    subtitle: "Shillong · Cherrapunji · Kaziranga",
    location: "Meghalaya",
    state: "Meghalaya",
    duration: "6N / 7D",
    price: 27999,
    originalPrice: 33499,
    rating: 4.8,
    reviews: 76,
    badge: "Offbeat",
    country: "India",
    image:
      "https://images.pexels.com/photos/18158726/pexels-photo-18158726.jpeg",
    highlights: ["Living root bridges", "Waterfalls", "Wildlife safari"],
    inclusions: ["Boutique stays", "Breakfast", "Private cab"],
    groupSize: "2–10 travellers",
    description:
      "Misty hills, cascading falls, and one-horned rhinos — India's untouched northeast unveiled.",
  },
  {
    id: "andaman-island",
    slug: "andaman-island-6n",
    title: "Andaman Island Escape",
    subtitle: "Port Blair · Havelock · Neil",
    location: "Andaman",
    state: "Andaman and Nicobar",
    duration: "5N / 6D",
    price: 29999,
    originalPrice: 35999,
    rating: 4.8,
    reviews: 134,
    badge: "Island Life",
    famous: true,
    country: "India",
    image:
      "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=900&q=80",
    highlights: ["Radhanagar Beach", "Scuba diving", "Cellular Jail"],
    inclusions: ["Beach resort", "Ferry tickets", "Breakfast"],
    groupSize: "2–12 travellers",
    description:
      "Turquoise waters, coral reefs, and tropical sunsets on India's most stunning archipelago.",
  },
  {
    id: "varanasi-spiritual",
    slug: "varanasi-spiritual-4n",
    title: "Varanasi Spiritual Trail",
    subtitle: "Ghats · Sarnath · Ganga Aarti",
    location: "Uttar Pradesh",
    state: "Uttar Pradesh",
    duration: "3N / 4D",
    price: 14999,
    originalPrice: 18999,
    rating: 4.7,
    reviews: 98,
    badge: "Cultural",
    country: "India",
    image:
      "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=900&q=80",
    highlights: ["Ganga aarti", "Boat ride", "Sarnath tour"],
    inclusions: ["Heritage hotel", "Breakfast", "Guide"],
    groupSize: "2–15 travellers",
    description:
      "Ancient ghats, evening aarti ceremonies, and the spiritual heart of India on the Ganges.",
  },
  {
    id: "gujarat-rann",
    slug: "gujarat-rann-5n",
    title: "Gujarat Rann Utsav",
    subtitle: "Kutch · Bhuj · Mandvi",
    location: "Gujarat",
    state: "Gujarat",
    duration: "4N / 5D",
    price: 21499,
    originalPrice: 25999,
    rating: 4.8,
    reviews: 87,
    badge: "Festival",
    country: "India",
    image:
      "https://images.pexels.com/photos/34568381/pexels-photo-34568381.jpeg",
    highlights: ["White desert", "Rann Utsav", "Handicraft villages"],
    inclusions: ["Tent stay", "All meals", "Cultural shows"],
    groupSize: "2–20 travellers",
    description:
      "Full-moon white desert magic, folk music, and vibrant Kutchi culture under starlit skies.",
  },
  {
    id: "ooty-nilgiris",
    slug: "ooty-nilgiris-4n",
    title: "Ooty & Nilgiris",
    subtitle: "Ooty · Coonoor · Kotagiri",
    location: "Tamil Nadu",
    state: "Tamil Nadu",
    duration: "3N / 4D",
    price: 17999,
    originalPrice: 21999,
    rating: 4.7,
    reviews: 145,
    badge: "Hill Station",
    country: "India",
    image:
      "https://images.pexels.com/photos/12388203/pexels-photo-12388203.jpeg",
    highlights: ["Toy train", "Tea estates", "Botanical gardens"],
    inclusions: ["Resort stay", "Breakfast", "Sightseeing"],
    groupSize: "2–10 travellers",
    description:
      "Misty Nilgiri hills, colonial charm, and fragrant tea gardens in South India's queen of hills.",
  },
  {
    id: "dubai-luxury",
    slug: "dubai-luxury-5n",
    title: "Dubai Luxury Escape",
    subtitle: "Downtown · Marina · Desert",
    location: "Dubai",
    state: "Dubai",
    duration: "4N / 5D",
    price: 54999,
    originalPrice: 64999,
    rating: 4.9,
    reviews: 167,
    badge: "International",
    famous: true,
    country: "Dubai",
    image:
      "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=900&q=80",
    highlights: ["Burj Khalifa", "Desert safari", "Dhow cruise"],
    inclusions: ["5★ Hotel", "Visa assist", "Transfers"],
    groupSize: "2–12 travellers",
    description:
      "Skyline views, desert adventures, and world-class shopping in the city of superlatives.",
  },
  {
    id: "nepal-himalayan",
    slug: "nepal-himalayan-6n",
    title: "Nepal Himalayan Trek",
    subtitle: "Kathmandu · Pokhara · Nagarkot",
    location: "Nepal",
    state: "Nepal",
    duration: "5N / 6D",
    price: 32999,
    originalPrice: 38999,
    rating: 4.8,
    reviews: 93,
    badge: "International",
    famous: true,
    country: "Nepal",
    image:
      "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=900&q=80",
    highlights: ["Annapurna views", "Phewa Lake", "Temple tours"],
    inclusions: ["Hotels", "Breakfast", "Domestic flights"],
    groupSize: "2–10 travellers",
    description:
      "Himalayan panoramas, lakeside Pokhara, and ancient Kathmandu valleys in one seamless trip.",
  },
  {
    id: "sikkim-darjeeling",
    slug: "sikkim-darjeeling-6n",
    title: "Sikkim & Darjeeling",
    subtitle: "Gangtok · Tsomgo · Darjeeling",
    location: "Sikkim",
    state: "Sikkim",
    duration: "5N / 6D",
    price: 26499,
    originalPrice: 31499,
    rating: 4.9,
    reviews: 118,
    badge: "Scenic",
    country: "India",
    image:
      "https://images.pexels.com/photos/17332516/pexels-photo-17332516.jpeg",
    highlights: ["Kanchenjunga views", "Tea gardens", "Buddhist monasteries"],
    inclusions: ["Hotels", "Permits", "Breakfast", "Cab"],
    groupSize: "2–12 travellers",
    description:
      "Snow peaks, prayer flags, and world-famous tea estates across Sikkim and Darjeeling.",
  },
  {
    id: "thailand-tropical",
    slug: "thailand-tropical-6n",
    title: "Thailand Tropical Getaway",
    subtitle: "Bangkok · Phuket · Phi Phi",
    location: "Thailand",
    state: "Thailand",
    duration: "5N / 6D",
    price: 44999,
    originalPrice: 52999,
    rating: 4.8,
    reviews: 201,
    badge: "International",
    country: "Thailand",
    image:
      "https://images.pexels.com/photos/2611495/pexels-photo-2611495.jpeg",
    highlights: ["Island hopping", "Thai cuisine", "Temple tours"],
    inclusions: ["4★ Resorts", "Flights assist", "Transfers"],
    groupSize: "2–15 travellers",
    description:
      "Golden temples, turquoise islands, and vibrant street food across Bangkok and the Andaman coast.",
  },
  {
    id: "bhutan-serenity",
    slug: "bhutan-serenity-6n",
    title: "Bhutan Serenity",
    subtitle: "Paro · Thimphu · Punakha",
    location: "Bhutan",
    state: "Bhutan",
    duration: "5N / 6D",
    price: 38999,
    originalPrice: 45999,
    rating: 4.9,
    reviews: 64,
    badge: "International",
    famous: true,
    country: "Bhutan",
    image: "",
    highlights: ["Tiger's Nest", "Dzong fortresses", "Himalayan valleys"],
    inclusions: ["Hotels", "SDF fees assist", "Guide", "Transfers"],
    groupSize: "2–10 travellers",
    description: "Prayer flags, cliffside monasteries, and the culture of Gross National Happiness.",
  },
  {
    id: "maldives-paradise",
    slug: "maldives-paradise-5n",
    title: "Maldives Paradise",
    subtitle: "Malé · Water villa · Snorkelling",
    location: "Maldives",
    state: "Maldives",
    duration: "4N / 5D",
    price: 62999,
    originalPrice: 74999,
    rating: 4.9,
    reviews: 88,
    badge: "Honeymoon",
    famous: true,
    country: "Maldives",
    image: "",
    highlights: ["Overwater villa", "Coral reefs", "Sunset cruise"],
    inclusions: ["Resort stay", "Speedboat transfers", "Breakfast"],
    groupSize: "2 travellers",
    description: "Turquoise lagoons and barefoot luxury on India's favourite island escape.",
  },
  {
    id: "singapore-city",
    slug: "singapore-city-4n",
    title: "Singapore City Break",
    subtitle: "Marina Bay · Sentosa · Gardens",
    location: "Singapore",
    state: "Singapore",
    duration: "3N / 4D",
    price: 48999,
    originalPrice: 56999,
    rating: 4.8,
    reviews: 112,
    badge: "International",
    country: "Singapore",
    image: "",
    highlights: ["Marina Bay Sands", "Night Safari", "Universal Studios"],
    inclusions: ["4★ Hotel", "Airport transfers", "City pass"],
    groupSize: "2–8 travellers",
    description: "Futuristic skyline, hawker food trails, and family-friendly attractions.",
  },
  {
    id: "malaysia-twin",
    slug: "malaysia-twin-6n",
    title: "Malaysia Twin Cities",
    subtitle: "Kuala Lumpur · Langkawi",
    location: "Malaysia",
    state: "Malaysia",
    duration: "5N / 6D",
    price: 41999,
    originalPrice: 49999,
    rating: 4.7,
    reviews: 76,
    badge: "International",
    country: "Malaysia",
    image: "",
    highlights: ["Petronas Towers", "Langkawi cable car", "Street food"],
    inclusions: ["Hotels", "Domestic flight", "Breakfast"],
    groupSize: "2–12 travellers",
    description: "Urban buzz in KL and island calm in Langkawi in one seamless trip.",
  },
  {
    id: "karnataka-heritage",
    slug: "karnataka-heritage-5n",
    title: "Karnataka Heritage",
    subtitle: "Bangalore · Mysore · Hampi",
    location: "Karnataka",
    state: "Karnataka",
    duration: "4N / 5D",
    price: 20999,
    originalPrice: 25499,
    rating: 4.8,
    reviews: 91,
    badge: "Heritage Pick",
    country: "India",
    image: "",
    highlights: ["Mysore Palace", "Hampi ruins", "Coorg coffee"],
    inclusions: ["Heritage hotels", "Breakfast", "Private cab"],
    groupSize: "2–15 travellers",
    description: "Royal palaces, UNESCO ruins, and misty coffee country in South India.",
  },
  {
    id: "punjab-golden",
    slug: "punjab-golden-3n",
    title: "Punjab Golden Triangle",
    subtitle: "Amritsar · Wagah · Anandpur",
    location: "Punjab",
    state: "Punjab",
    duration: "2N / 3D",
    price: 12999,
    originalPrice: 15999,
    rating: 4.8,
    reviews: 134,
    badge: "Spiritual",
    country: "India",
    image: "",
    highlights: ["Golden Temple", "Wagah border", "Punjabi cuisine"],
    inclusions: ["Hotel near temple", "Breakfast", "Local guide"],
    groupSize: "2–20 travellers",
    description: "Sacred Harmandir Sahib, vibrant bazaars, and the heartland of Punjab.",
  },
  {
    id: "assam-wildlife",
    slug: "assam-wildlife-5n",
    title: "Assam Wildlife Safari",
    subtitle: "Kaziranga · Guwahati · Tea estates",
    location: "Assam",
    state: "Assam",
    duration: "4N / 5D",
    price: 23499,
    originalPrice: 27999,
    rating: 4.8,
    reviews: 58,
    badge: "Adventure",
    country: "India",
    image: "",
    highlights: ["Rhino safari", "Brahmaputra cruise", "Tea tasting"],
    inclusions: ["Jungle lodge", "Safari jeep", "All meals"],
    groupSize: "2–8 travellers",
    description: "One-horned rhinos, lush tea gardens, and the mighty Brahmaputra.",
  },
  {
    id: "bali-retreat",
    slug: "bali-retreat-6n",
    title: "Bali Island Retreat",
    subtitle: "Ubud · Seminyak · Nusa Penida",
    location: "Bali",
    state: "Indonesia",
    duration: "5N / 6D",
    price: 52999,
    originalPrice: 61999,
    rating: 4.9,
    reviews: 143,
    badge: "International",
    famous: true,
    country: "Indonesia",
    image: "",
    highlights: ["Rice terraces", "Temple tours", "Beach clubs"],
    inclusions: ["Villa stay", "Airport pickup", "Breakfast"],
    groupSize: "2–12 travellers",
    description: "Rice paddies, cliff temples, and sunset beaches on Bali.",
  },
  {
    id: "sri-lanka-circle",
    slug: "sri-lanka-circle-7n",
    title: "Sri Lanka Circle Tour",
    subtitle: "Colombo · Kandy · Ella · Galle",
    location: "Sri Lanka",
    state: "Sri Lanka",
    duration: "6N / 7D",
    price: 36999,
    originalPrice: 43999,
    rating: 4.8,
    reviews: 95,
    badge: "International",
    country: "Sri Lanka",
    image: "",
    highlights: ["Tea country", "Sigiriya rock", "Coastal train"],
    inclusions: ["Boutique hotels", "Train tickets", "Breakfast"],
    groupSize: "2–10 travellers",
    description: "Ancient kingdoms, hill-country trains, and Indian Ocean beaches.",
  },
  {
    id: "mumbai-getaway",
    slug: "mumbai-getaway-3n",
    title: "Mumbai City Getaway",
    subtitle: "Gateway · Marine Drive · Elephanta",
    location: "Mumbai",
    state: "Maharashtra",
    duration: "2N / 3D",
    price: 14999,
    originalPrice: 18499,
    rating: 4.7,
    reviews: 156,
    badge: "Weekend Special",
    country: "India",
    image: "",
    highlights: ["Gateway of India", "Bollywood tour", "Coastal drive"],
    inclusions: ["City hotel", "Breakfast", "Sightseeing cab"],
    groupSize: "2–12 travellers",
    description: "Maximum city energy, heritage walks, and sea-facing sunsets in Mumbai.",
  },
  {
    id: "coorg-nature",
    slug: "coorg-nature-4n",
    title: "Coorg Nature Escape",
    subtitle: "Madikeri · Abbey Falls · Plantations",
    location: "Coorg",
    state: "Karnataka",
    duration: "3N / 4D",
    price: 17999,
    originalPrice: 21999,
    rating: 4.8,
    reviews: 82,
    badge: "Serene Escape",
    country: "India",
    image: "",
    highlights: ["Coffee estates", "Waterfalls", "Homestay stays"],
    inclusions: ["Plantation stay", "Breakfast", "Local transfers"],
    groupSize: "2–8 travellers",
    description: "Misty hills, aromatic coffee plantations, and slow travel in the Scotland of India.",
  },
  {
    id: "pondicherry-coastal",
    slug: "pondicherry-coastal-3n",
    title: "Pondicherry Coastal",
    subtitle: "French Quarter · Auroville · Beaches",
    location: "Pondicherry",
    state: "Pondicherry",
    duration: "2N / 3D",
    price: 13999,
    originalPrice: 16999,
    rating: 4.7,
    reviews: 71,
    badge: "Weekend Special",
    country: "India",
    image: "",
    highlights: ["French lanes", "Promenade Beach", "Auroville visit"],
    inclusions: ["Boutique hotel", "Breakfast", "Bike rental"],
    groupSize: "2–10 travellers",
    description: "Colonial charm, café culture, and quiet beaches on the Coromandel coast.",
  },
];

for (const pkg of TOUR_PACKAGES) {
  pkg.image = getPackageImage(pkg);
}

export const PACKAGE_FAQ = [
  {
    q: "What is included in a Demand Setu tour package?",
    a: "Most packages include accommodation, daily breakfast (or all meals where specified), private or shared transfers, sightseeing, and on-ground support. International packages may include visa assistance. Exact inclusions are listed on each package card — our team confirms everything before you book.",
  },
  {
    q: "Can I customise dates, hotels, or the itinerary?",
    a: "Yes. Every package can be tailored to your travel dates, group size, hotel preferences, and special requests. Click View detail on any package or use the search form — our specialists will share a revised quote within a few hours.",
  },
  {
    q: "Do you operate tours outside India?",
    a: "Absolutely. We curate packages across Nepal, Bhutan, Thailand, Dubai, Sri Lanka, and more. Select a country in the search widget or browse Explore Countries to start planning your international trip.",
  },
  {
    q: "How do I book and pay for a tour package?",
    a: "Submit an enquiry through any package card or the search form. Our team shares a detailed itinerary and quote. Once confirmed, you can pay securely online or via bank transfer. We provide booking confirmation and a dedicated trip coordinator.",
  },
  {
    q: "What is your cancellation and refund policy?",
    a: "Cancellation terms vary by package and season. Generally, free cancellation is available up to 15–30 days before departure; closer dates may incur partial charges. Your quote will include clear cancellation terms before payment.",
  },
  {
    q: "Are group discounts available?",
    a: "Yes — groups of 6 or more travellers receive special rates on most domestic and international packages. Corporate outings, school trips, and wedding groups are welcome. Mention your group size in the enquiry form.",
  },
  {
    q: "Is travel insurance included?",
    a: "Basic travel insurance can be added to any package on request. We strongly recommend insurance for adventure routes (Ladakh, Spiti, treks) and all international trips. Ask our team when you enquire.",
  },
  {
    q: "Who do I contact during the trip?",
    a: "You get 24/7 orange-line support from booking through return. A dedicated trip coordinator shares driver and hotel contacts before departure, and our helpline (+91 8353056000) is always available.",
  },
];

export const PACKAGE_TESTIMONIALS = [
  {
    name: "Priya Sharma",
    location: "Mumbai",
    package: "Ladakh Escape",
    rating: 5,
    text: "Flawless from enquiry to return. Pangong stay, permits, cab — everything handled. Best trip we've ever taken.",
    avatar: "PS",
  },
  {
    name: "Rahul & Ananya",
    location: "Bangalore",
    package: "Himachal Honeymoon",
    rating: 5,
    text: "They customised our Manali itinerary with a surprise candlelight dinner. Felt truly personal and premium.",
    avatar: "RA",
  },
  {
    name: "Vikram Mehta",
    location: "Delhi",
    package: "Dubai Luxury Escape",
    rating: 5,
    text: "International trip made easy — visa help, airport pickup, desert safari all pre-booked. Zero stress.",
    avatar: "VM",
  },
  {
    name: "Sneha Reddy",
    location: "Hyderabad",
    package: "Kerala Backwaters",
    rating: 5,
    text: "Houseboat experience was magical. Demand Setu team checked in daily. Already booked Rajasthan for December.",
    avatar: "SR",
  },
];

export const PACKAGE_DESTINATIONS = [
  "All",
  ...Array.from(new Set(TOUR_PACKAGES.map((p) => p.state))),
];

export function getPackageBySlug(slug) {
  return TOUR_PACKAGES.find((p) => p.slug === slug) ?? null;
}

export function getFamousPackages() {
  const famous = TOUR_PACKAGES.filter((p) => p.famous);
  return famous.length > 0 ? famous : TOUR_PACKAGES.slice(0, 8);
}

export function getAllPackages() {
  return TOUR_PACKAGES;
}

export function getPackageCategories() {
  return ["All", "India", "International", "Adventure", "Spiritual", "Beach"];
}

export function filterPackages(packages, category) {
  if (!category || category === "All") return packages;
  if (category === "India") return packages.filter((p) => p.country === "India");
  if (category === "International")
    return packages.filter((p) => p.country !== "India");
  if (category === "Adventure")
    return packages.filter((p) =>
      ["Adventure", "Offbeat", "Island Life"].includes(p.badge)
    );
  if (category === "Spiritual")
    return packages.filter((p) =>
      ["Spiritual", "Cultural", "Heritage Pick"].includes(p.badge)
    );
  if (category === "Beach")
    return packages.filter((p) =>
      ["Weekend Special", "Island Life", "Serene Escape"].includes(p.badge)
    );
  return packages;
}

export function formatPackagePrice(amount) {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(amount);
}
